# setup
language: python
dist: xenial
python:
  - "3.7"

# command to install dependencies
install:
  - "pip install pipenv"
  - "pipenv sync --dev"

# command to run tests
script:
  # Run unit tests
  - "pipenv run pytest --verbose"

  # Only check fatal (1), error (2) and warning (4) exit codes from pylint.
  - "pipenv run pylint --rcfile ./pylintrc --output-format colorized promqtt; exit $(($? & 7))"
